# [作業重點]
觀察函數說明，要如何切出固定大小的測試集?

作業
假設我們資料中類別的數量並不均衡，在評估準確率時可能會有所偏頗，試著切分出 y_test 中，0 類別與 1 類別的數量是一樣的 (亦即 y_test 的類別是均衡的)

In [218]:
from sklearn.model_selection import train_test_split
import numpy as np

In [219]:
X = np.arange(1000).reshape(200, 5)
y = np.zeros(200)
y[:40] = 1

In [220]:
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

可以看見 y 類別中，有 160 個 類別 0，40 個 類別 1 ，請試著使用 train_test_split 函數，切分出 y_test 中能各有 10 筆類別 0 與 10 筆類別 1 。(HINT: 參考函數中的 test_size，可針對不同類別各自作切分後再合併)

In [221]:
#前面40行為1,所以取40以前就為1
from sklearn.model_selection import train_test_split
X1_train, X1_test, y1_train, y1_test = train_test_split(X[:30], y[:30], test_size=10, random_state=42)
print(f'{X1_train.shape} {X1_test.shape} {y1_train.shape} {y1_test.shape}')
y1_test

(20, 5) (10, 5) (20,) (10,)


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [222]:
#前面40行為1,所以取40以後就為0
X0_train, X0_test, y0_train, y0_test = train_test_split(X[40:], y[40:], test_size=10, random_state=42)
print(f'{X0_train.shape} {X0_test.shape} {y0_train.shape} {y0_test.shape}')
y0_test

(150, 5) (10, 5) (150,) (10,)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [223]:
y_test = np.concatenate((y1_test, y0_test))
print(y_test.shape)
y_test

(20,)


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])